version: 2
updates:
  # Update npm packages in the main project
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      development-dependencies:
        patterns:
          - "eslint*"
          - "@testing-library/*"
          - "prettier"
        update-types:
          - "minor"
          - "patch"
      production-dependencies:
        patterns:
          - "react*"
          - "@firebase/*"
          - "firebase"
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "ethers"
        versions: ["7.x"]  # Stay on v6 for compatibility
    
  # Update npm packages in Firebase Functions
  - package-ecosystem: "npm"
    directory: "/firebase/functions"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    
  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    
