// src/components/tournament/TournamentCard.js
import React, { useState } from 'react';
import PropTypes from 'prop-types';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';
import PrizePool from './PrizePool';
import TournamentRegistration from './TournamentRegistration';
import { useAuth } from '../../hooks/useAuth';
import '../../styles/components/TournamentCard.css';
/**
 * Tournament Card Component
  * Displays details about a single tournament with registration options
   */
   const TournamentCard = ({ tournament }) => {
     const { user } = useAuth();
       const navigate = useNavigate();
         const [showPrizePool, setShowPrizePool] = useState(false);
           
             // Format date to readable string
               const formatDate = (timestamp) => {
                   if (!timestamp) return 'TBD';
                       
                           // Handle both Firestore timestamp and JS Date objects
                               const date = timestamp.seconds 
                                     ? new Date(timestamp.seconds * 1000) 
                                           : new Date(timestamp);
                                                 
                                                     return format(date, 'MMM d, yyyy h:mm a');
                                                       };
                                                         
                                                           // Get tournament status badge with appropriate styling
                                                             const getStatusBadge = () => {
                                                                 const statusClasses = {
                                                                       upcoming: 'status-badge upcoming',
                                                                             active: 'status-badge active',
                                                                                   completed: 'status-badge completed'
                                                                                       };
                                                                                           
                                                                                               return (
                                                                                                     <span className={statusClasses[tournament.status] || 'status-badge'}>
                                                                                                             {tournament.status.charAt(0).toUpperCase() + tournament.status.slice(1)}
                                                                                                                   </span>
                                                                                                                       );
                                                                                                                         };
                                                                                                                           
                                                                                                                             // Get entry fee based on tournament type
                                                                                                                               const getEntryFee = () => {
                                                                                                                                   return tournament.type === 'mini' ? '1 USDT' : '10 USDT';
                                                                                                                                     };
                                                                                                                                       
                                                                                                                                         // Get prize pool summary
                                                                                                                                           const getPrizePoolSummary = () => {
                                                                                                                                               if (tournament.type === 'mini') {
                                                                                                                                                     return '10,500 USDT + 1,050 DINO';
                                                                                                                                                         } else {
                                                                                                                                                               return '605,000 USDT + 60,500 DINO';
                                                                                                                                                                   }
                                                                                                                                                                     };
                                                                                                                                                                       
                                                                                                                                                                         // Handle view leaderboard click
                                                                                                                                                                           const handleViewLeaderboard = () => {
                                                                                                                                                                               navigate(`/tournament/${tournament.id}/leaderboard`);
                                                                                                                                                                                 };
                                                                                                                                                                                   
                                                                                                                                                                                     return (
                                                                                                                                                                                         <div className="tournament-card">
                                                                                                                                                                                               <div className="tournament-card-header">
                                                                                                                                                                                                       <h3>{tournament.name}</h3>
                                                                                                                                                                                                               {getStatusBadge()}
                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                           
                                                                                                                                                                                                                                 <div className="tournament-card-body">
                                                                                                                                                                                                                                         <div className="tournament-info">
                                                                                                                                                                                                                                                   <div className="info-row">
                                                                                                                                                                                                                                                               <span className="info-label">Type:</span>
                                                                                                                                                                                                                                                                           <span className="info-value">{tournament.type === 'mini' ? 'Mini Tournament' : 'Grand Tournament'}</span>
                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                                                         <div className="info-row">
                                                                                                                                                                                                                                                                                                                     <span className="info-label">Entry Fee:</span>
                                                                                                                                                                                                                                                                                                                                 <span className="info-value">{getEntryFee()}</span>
                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                                               <div className="info-row">
                                                                                                                                                                                                                                                                                                                                                                           <span className="info-label">Start Date:</span>
                                                                                                                                                                                                                                                                                                                                                                                       <span className="info-value">{formatDate(tournament.startDate)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="info-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                 <span className="info-label">End Date:</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                             <span className="info-value">{formatDate(tournament.endDate)}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <div className="info-row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <span className="info-label">Prize Pool:</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <span className="info-value prize-pool">{getPrizePoolSummary()}</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="tournament-actions">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           className="btn btn-secondary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       onClick={() => setShowPrizePool(!showPrizePool)}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {showPrizePool ? 'Hide Prize Details' : 'View Prize Details'}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           <button 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       className="btn btn-primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   onClick={handleViewLeaderboard}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         View Leaderboard
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       {tournament.status === 'active' && user && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <TournamentRegistration 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 tournamentId={tournament.id} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               tournamentType={tournament.type}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             entryFee={tournament.type === 'mini' ? 1 : 10}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             {showPrizePool && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     <div className="prize-pool-details">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               <PrizePool tournamentType={tournament.type} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   TournamentCard.propTypes = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     tournament: PropTypes.shape({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         id: PropTypes.string.isRequired,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             name: PropTypes.string.isRequired,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 type: PropTypes.oneOf(['mini', 'grand']).isRequired,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     startDate: PropTypes.oneOfType([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           PropTypes.object, // For Firestore Timestamp
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 PropTypes.string, // For string dates
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       PropTypes.number  // For numeric timestamps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           ]).isRequired,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               endDate: PropTypes.oneOfType([
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     PropTypes.object,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           PropTypes.string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 PropTypes.number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ]).isRequired,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         status: PropTypes.oneOf(['upcoming', 'active', 'completed']).isRequired
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }).isRequired
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           export default TournamentCard;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           