// src/components/auth/GoogleSignIn.js
import React, { useState } from 'react';
import { signInWithPopup } from 'firebase/auth';
import { auth, googleProvider, db } from '../../config/firebase';
import { doc, setDoc, getDoc, serverTimestamp } from 'firebase/firestore';
import { useNavigate } from 'react-router-dom';
import Button from '../common/Button';
import { SUCCESS_MESSAGES, ERROR_MESSAGES } from '../../config/constants';
import PropTypes from 'prop-types';
import '../../styles/components/GoogleSignIn.css';

/**
 * GoogleSignIn Component
  * 
   * Provides a button to sign in with a Google account using Firebase Authentication.
    * Handles user creation in Firestore if the user does not already exist.
     * 
      * @param {Object} props - Component props
       * @param {string} [props.variant='primary'] - Button variant
        * @param {string} [props.size='medium'] - Button size
         * @param {string} [props.className] - Additional CSS class names
          * @param {Function} [props.onSuccess] - Callback function on successful sign-in
           * @param {Function} [props.onError] - Callback function on sign-in error
            * @param {boolean} [props.redirectToTournaments=true] - Whether to redirect to tournaments page after sign-in
             */
             const GoogleSignIn = ({
               variant = 'primary',
                 size = 'medium',
                   className = '',
                     onSuccess,
                       onError,
                         redirectToTournaments = true
                         }) => {
                           const [loading, setLoading] = useState(false);
                             const [error, setError] = useState(null);
                               const navigate = useNavigate();

                                 const handleSignIn = async () => {
                                     setLoading(true);
                                         setError(null);

                                             try {
                                                   const result = await signInWithPopup(auth, googleProvider);
                                                         const user = result.user;

                                                               // Check if user exists in Firestore
                                                                     const userRef = doc(db, "users", user.uid);
                                                                           const userSnap = await getDoc(userRef);

                                                                                 if (!userSnap.exists()) {
                                                                                         // Generate a unique referral code based on user ID
                                                                                                 const referralCode = user.uid.substring(0, 8).toUpperCase();
                                                                                                         
                                                                                                                 // Create a new user in Firestore
                                                                                                                         await setDoc(userRef, {
                                                                                                                                   email: user.email,
                                                                                                                                             displayName: user.displayName || 'User',
                                                                                                                                                       photoURL: user.photoURL,
                                                                                                                                                                 createdAt: serverTimestamp(),
                                                                                                                                                                           miniTournamentPaid: false,
                                                                                                                                                                                     grandTournamentPaid: false,
                                                                                                                                                                                               referralCode: referralCode,
                                                                                                                                                                                                         referredBy: null,
                                                                                                                                                                                                                   balance: 0,
                                                                                                                                                                                                                             referralBalance: 0,
                                                                                                                                                                                                                                       activeBooster: null
                                                                                                                                                                                                                                               });
                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               console.log("New user created with referral code:", referralCode);
                                                                                                                                                                                                                                                                     }

                                                                                                                                                                                                                                                                           // Call success callback if provided
                                                                                                                                                                                                                                                                                 if (onSuccess) {
                                                                                                                                                                                                                                                                                         onSuccess(user);
                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                           // Redirect to tournaments page if specified
                                                                                                                                                                                                                                                                                                                 if (redirectToTournaments) {
                                                                                                                                                                                                                                                                                                                         navigate('/tournaments');
                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                                                                                                           console.log(SUCCESS_MESSAGES.AUTH.SIGN_IN_SUCCESS);
                                                                                                                                                                                                                                                                                                                                               } catch (error) {
                                                                                                                                                                                                                                                                                                                                                     console.error("Error signing in with Google:", error);
                                                                                                                                                                                                                                                                                                                                                           setError(ERROR_MESSAGES.AUTH.SIGN_IN_FAILED);
                                                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                       // Call error callback if provided
                                                                                                                                                                                                                                                                                                                                                                             if (onError) {
                                                                                                                                                                                                                                                                                                                                                                                     onError(error);
                                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                               } finally {
                                                                                                                                                                                                                                                                                                                                                                                                     setLoading(false);
                                                                                                                                                                                                                                                                                                                                                                                                         }
                                                                                                                                                                                                                                                                                                                                                                                                           };

                                                                                                                                                                                                                                                                                                                                                                                                             return (
                                                                                                                                                                                                                                                                                                                                                                                                                 <div className="google-sign-in">
                                                                                                                                                                                                                                                                                                                                                                                                                       <Button 
                                                                                                                                                                                                                                                                                                                                                                                                                               variant={variant} 
                                                                                                                                                                                                                                                                                                                                                                                                                                       size={size} 
                                                                                                                                                                                                                                                                                                                                                                                                                                               onClick={handleSignIn} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                       loading={loading} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                               className={`google-sign-in-button ${className}`}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                     >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                             <span className="google-icon">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       <svg viewBox="0 0 24 24" width="18" height="18">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   <path
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 fill="currentColor"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               d="M12.545,10.239v3.821h5.445c-0.712,2.315-2.647,3.972-5.445,3.972c-3.332,0-6.033-2.701-6.033-6.032s2.701-6.032,6.033-6.032c1.498,0,2.866,0.549,3.921,1.453l2.814-2.814C17.503,2.988,15.139,2,12.545,2C7.021,2,2.543,6.477,2.543,12s4.478,10,10.002,10c8.396,0,10.249-7.85,9.426-11.748L12.545,10.239z"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </svg>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     Sign in with Google
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           </Button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 {error && <p className="google-sign-in-error">{error}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       GoogleSignIn.propTypes = {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         variant: PropTypes.string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           size: PropTypes.string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             className: PropTypes.string,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               onSuccess: PropTypes.func,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 onError: PropTypes.func,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   redirectToTournaments: PropTypes.bool
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   export default GoogleSignIn;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   